### ISSUE TITLE
Running the code without docker

### ISSUE THREAD

**Issue by dkhanna511** [noahcao/OC_SORT#101]
Hi, I was just wondering whether it is possible to run the code and benchmark it on several datasets without actual running a docker. I  am currently facing this error and I'm not sure how to solve this. 

` python3 tools/run_ocsort.py -f exps/example/mot/yolox_x_mix_mot20_ch.py -c pretrained/bytetrack_x_mot20.tar -b 1 -d 1 --fp16 --fuse --track_thresh 0.4 --mot20 --expn 1
Traceback (most recent call last):
  File "tools/run_ocsort.py", line 10, in <module>
    from yolox.evaluators import MOTEvaluator, MOTEvaluatorPublic
  File "/home/dheerajk/WACV-ICRA/OC_SORT/yolox/evaluators/__init__.py", line 7, in <module>
    from .mot_evaluator_dance import MOTEvaluator as MOTEvaluatorDance
  File "/home/dheerajk/WACV-ICRA/OC_SORT/yolox/evaluators/mot_evaluator_dance.py", line 15, in <module>
    from trackers.byte_tracker.byte_tracker import BYTETracker
  File "/home/dheerajk/WACV-ICRA/OC_SORT/trackers/byte_tracker/byte_tracker.py", line 10, in <module>
    from trackers.byte_tracker import matching
  File "/home/dheerajk/WACV-ICRA/OC_SORT/trackers/byte_tracker/matching.py", line 4, in <module>
    import lap
  File "/home/dheerajk/anaconda3/envs/ocsort/lib/python3.8/site-packages/lap/__init__.py", line 25, in <module>
    from ._lapjv import (
  File "__init__.pxd", line 199, in init lap._lapjv
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 96`

**Comment by noahcao** [comment]
Hi @dkhanna511 ,

In the [install instructions](https://github.com/noahcao/OC_SORT/blob/master/docs/INSTALL.md), we don't ask running with docker as necessary. Of course you can run without using a docker. 

When you'd like to benchmark it on several datasets, I guess what is needed is to align the dataset files with the default MOT-format.
