### ISSUE TITLE
ImportError: cannot import name '_C' from 'yolox' (*/OC_SORT/tools/yolox/__init__.py)

### ISSUE THREAD

**Issue by cj401** [noahcao/OC_SORT#125]
Hey @noahcao, thanks for sharing this work. 

with python3.9 and python3.10 (pytorch-2.3.0) on ubuntu 22.04, I am trying to reproduce the metrics with the following cli:

`python3 tools/run_ocsort.py -f exps/example/mot/yolox_x_ablation.py -c pretrained/ocsort_mot17_ablation.pth.tar -b 1 -d 1 --fp16 --fuse --expn mot17`

with detection running 

` access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  param_grad = param.grad
 11%|#1        | 299/2652 [00:40<05:11,  7.55it/s]2024-07-19 10:44:14 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-02-FRCNN.txt
 31%|###1      | 823/2652 [01:51<04:14,  7.17it/s]2024-07-19 10:45:26 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-04-FRCNN.txt
 47%|####6     | 1241/2652 [02:50<03:12,  7.33it/s]2024-07-19 10:46:25 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-05-FRCNN.txt
 57%|#####6    | 1503/2652 [03:26<02:35,  7.41it/s]2024-07-19 10:47:01 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-09-FRCNN.txt
 69%|######8   | 1829/2652 [04:11<01:52,  7.35it/s]2024-07-19 10:47:45 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-10-FRCNN.txt
 86%|########5 | 2278/2652 [05:12<00:51,  7.30it/s]2024-07-19 10:48:46 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-11-FRCNN.txt
100%|#########9| 2651/2652 [06:03<00:00,  7.40it/s]2024-07-19 10:49:37 | INFO     | utils.utils:32 - save results to evaldata/trackers/mot_challenge/MOT17-val/mot17_results/data/MOT17-13-FRCNN.txt
100%|##########| 2652/2652 [06:03<00:00,  7.30it/s]
`
however, when evaluating, it generates errors

`2024-07-19 10:49:37 | INFO     | yolox.evaluators.mot_evaluator:543 - Evaluate in main process...
2024-07-19 10:49:38 | INFO     | yolox.evaluators.mot_evaluator:572 - Loading and preparing results...
2024-07-19 10:49:39 | INFO     | yolox.evaluators.mot_evaluator:572 - DONE (t=0.40s)
2024-07-19 10:49:39 | INFO     | pycocotools.coco:366 - creating index...
2024-07-19 10:49:39 | INFO     | pycocotools.coco:366 - index created!
2024-07-19 10:49:39 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (86998), thread 'MainThread' (138029517096064):
Traceback (most recent call last):

File "/home/nvidia/Downloads/OC_SORT/tools/run_ocsort.py", line 211, in <module>
    launch(
    └ <function launch at 0x7d889b50b1f0>

> File "/home/nvidia/Downloads/OC_SORT/tools/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7d88c8732dc0>

  File "/home/nvidia/Downloads/OC_SORT/tools/run_ocsort.py", line 150, in main
    *_, summary = evaluator.evaluate_ocsort(
                  │         └ <function MOTEvaluator.evaluate_ocsort at 0x7d88967f8c10>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7d888f5a3070>

  File "/home/nvidia/Downloads/OC_SORT/tools/yolox/evaluators/mot_evaluator.py", line 502, in evaluate_ocsort
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 347.5862,    9.3185, 2651.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 302, 'category_id': 1, 'bbox': [889.6500244140625, 422.5500183105469, 137.699951171875, 520.425048828125], 'sco...
                   │    └ <function MOTEvaluator.evaluate_prediction at 0x7d88967f8d30>
                   └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7d888f5a3070>

  File "/home/nvidia/Downloads/OC_SORT/tools/yolox/evaluators/mot_evaluator.py", line 581, in evaluate_prediction
    from yolox.layers import COCOeval_opt as COCOeval

  File "/home/nvidia/Downloads/OC_SORT/tools/yolox/layers/__init__.py", line 5, in <module>
    from .fast_coco_eval_api import COCOeval_opt

  File "/home/nvidia/Downloads/OC_SORT/tools/yolox/layers/fast_coco_eval_api.py", line 13, in <module>
    from yolox import _C

ImportError: cannot import name '_C' from 'yolox' (/home/nvidia/Downloads/OC_SORT/tools/yolox/__init__.py)

`

tried various ways to for this error. Maybe I should run evaluation separately. I look forward to hearing from you.

**Comment by GodvFocus** [comment]
I think you can try running the command "python setup.py develop" in the terminal. I met the same problem before, and this command fixed it for me.
